# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - release
  - 0.4.5
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'include(Pkg.dir("DifferentialEquations")*"/test/ci_setup.jl"); include(Pkg.dir("DifferentialEquations")*"/test/pyplotsetup.jl"); Pkg.test("DifferentialEquations",coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("DifferentialEquations")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("DifferentialEquations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("DifferentialEquations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
addons:
  apt:
    packages:
      - gfortran
