site_name:           DifferentialEquations.jl
repo_url:            https://github.com/ChrisRackauckas/DifferentialEquations.jl
site_description:    Julia package for solving differential equations
site_author:         Chris Rackauckas
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  #- mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorial:
  - Ordinary Differential Equation Example: tutorials/ode.md
  - Stochastic Differential Equation Example: tutorials/sde.md
  - Poisson Equation Finite Element Method Example: tutorials/femPoisson.md
  - Heat Equation Finite Element Method Example: tutorials/femHeat.md
  - Stochastic Finite Element Examples: tutorials/femStochastic.md
- Manual:
  - Overview of DifferentialEquations.jl Usage: man/overview.md
  - Defining an ODE Problem: man/odeProblem.md
  - Defining an SDE Problem: man/sdeProblem.md
  - Defining a Finite Element Problem: man/femProblem.md
  - Defining a Stokes Problem: man/stokesProblem.md
  - Meshes: man/mesh.md
  - Information on Solvers: man/solvers.md
  - The Solution Type: man/solution.md
  - Plot Functions: man/plot.md
  - Convergence Simuations: man/convergence.md
- Internal Documentation:
  - Internal Finite Element Tools: internals/femTools.md
  - Extra Functions: internals/extras.md
  - Solver Helpers: internals/solverHelpers.md
